name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Update Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy@v1
        with:
          cluster: sample-cluster
          service: ecr-ecs
          image: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          aws-region: us-east-1
